In [1]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('../data/raw/ipl_matches.csv', low_memory=False)
df.shape
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [7]:
df=df.drop(columns=['Unnamed: 0'],errors='ignore')

In [8]:
df

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283673,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,96,3,NaN,NaN,2,2,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283674,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,97,3,NaN,NaN,2,3,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283675,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,2,16.2,...,98,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283676,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,98,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283677,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,99,3,NaN,NaN,10,5,0,"('MP Stoinis', 'P Simran Singh')",NaN,False

In [9]:
df['date']=pd.to_datetime(df['date'], errors='coerce')

In [10]:
df

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283673,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,96,3,NaN,NaN,2,2,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283674,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,97,3,NaN,NaN,2,3,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283675,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,2,16.2,...,98,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283676,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,98,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283677,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,99,3,NaN,NaN,10,5,0,"('MP Stoinis', 'P Simran Singh')",NaN,False

In [11]:
df=df.drop(columns=['power_surge_start'], errors='ignore')

In [12]:
df

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283673,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,189,96,3,NaN,2,2,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283674,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,189,97,3,NaN,2,3,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283675,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,2,16.2,...,193,98,3,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283676,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,194,98,3,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283677,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,198,99,3,NaN,10,5,0,"('MP Stoinis', 'P Simran Singh')",NaN,False

In [13]:
df['wicket_kind'] = df['wicket_kind'].fillna('No Wicket')
df['player_out'] = df['player_out'].fillna('None')
df['fielders'] = df['fielders'].fillna('None')

df['extra_type'] = df['extra_type'].fillna('None')

df['review_decision'] = df['review_decision'].fillna('No Review')
df['umpire'] = df['umpire'].fillna('Unknown')

In [14]:
df

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283673,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,189,96,3,NaN,2,2,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283674,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,16.1,...,189,97,3,NaN,2,3,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283675,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,2,16.2,...,193,98,3,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283676,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,194,98,3,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283677,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,16.3,...,198,99,3,NaN,10,5,0,"('MP Stoinis', 'P Simran Singh')",NaN,False

In [15]:
df = df.drop_duplicates()

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 63 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           283678 non-null  int64
 1   date               283678 non-null  datetime64[us]
 2   match_type         283678 non-null  str
 3   event_name         283678 non-null  str
 4   innings            283678 non-null  int64
 5   batting_team       283678 non-null  str
 6   bowling_team       283678 non-null  str
 7   over               283678 non-null  int64
 8   ball               283678 non-null  int64
 9   ball_no            283678 non-null  float64
 10  batter             283678 non-null  str
 11  bat_pos            283678 non-null  int64
 12  runs_batter        283678 non-null  int64
 13  balls_faced        283678 non-null  int64
 14  bowler             283678 non-null  str
 15  valid_ball         283678 non-null  int64
 16  runs_extras        283678 non-null  int64
 17  runs_total         283678 non-null  int64
 18  runs_bowler        283678 non-null  int64
 19  runs_not_boundary  283678 non-null  bool
 20  extra_type         283678 non-null  str
 21  non_striker        283678 non-null  str
 22  non_striker_pos    283678 non-null  int64
 23  wicket_kind        283678 non-null  str
 24  player_out         283678 non-null  str
 25  fielders           283678 non-null  str
 26  runs_target        136510 non-null  float64
 27  review_batter      907 non-null     str
 28  team_reviewed      907 non-null     str
 29  review_decision    283678 non-null  str
 30  umpire             283678 non-null  str
 31  umpires_call       283678 non-null  bool
 32  player_of_match    283678 non-null  str
 33  match_won_by       283678 non-null  str
 34  win_outcome        278954 non-null  str
 35  toss_winner        283678 non-null  str
 36  toss_decision      283678 non-null  str
 37  venue              283678 non-null  str
 38  city               283678 non-null  str
 39  day                283678 non-null  int64
 40  month              283678 non-null  int64
 41  year               283678 non-null  int64
 42  season             283678 non-null  str
 43  gender             283678 non-null  str
 44  team_type          283678 non-null  str
 45  superover_winner   3896 non-null    str
 46  result_type        4724 non-null    str
 47  method             3890 non-null    str
 48  balls_per_over     283678 non-null  int64
 49  overs              283678 non-null  int64
 50  event_match_no     283678 non-null  str
 51  stage              283678 non-null  str
 52  match_number       283678 non-null  str
 53  team_runs          283678 non-null  int64
 54  team_balls         283678 non-null  int64
 55  team_wicket        283678 non-null  int64
 56  new_batter         13593 non-null   str
 57  batter_runs        283678 non-null  int64
 58  batter_balls       283678 non-null  int64
 59  bowler_wicket      283678 non-null  int64
 60  batting_partners   283678 non-null  str
 61  next_batter        13593 non-null   str
 62  striker_out        283678 non-null  bool
dtypes: bool(3), datetime64[us](1), float64(2), int64(23), str(34)
memory usage: 130.7 MB

In [17]:
numeric_cols = [
    'runs_batter', 'runs_total', 'runs_extras',
    'team_runs', 'team_wicket'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [18]:
team_mapping = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Deccan Chargers': 'Sunrisers Hyderabad'
}

df['batting_team'] = df['batting_team'].replace(team_mapping)
df['bowling_team'] = df['bowling_team'].replace(team_mapping)
df['toss_winner'] = df['toss_winner'].replace(team_mapping)
df['match_won_by'] = df['match_won_by'].replace(team_mapping)

In [19]:
# Ball number in innings
df['total_balls'] = df['over'] * 6 + df['ball']

# Is boundary
df['is_boundary'] = df['runs_batter'].apply(lambda x: 1 if x in [4,6] else 0)

# Is wicket
df['is_wicket'] = df['wicket_kind'].apply(lambda x: 0 if x == 'No Wicket' else 1)

# Strike rate per ball (approx feature)
df['strike_rate'] = (df['runs_batter'] / df['balls_faced'].replace(0, np.nan)) * 100

In [20]:
df.isnull().sum().sort_values(ascending=False).head(10)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 67 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           283678 non-null  int64
 1   date               283678 non-null  datetime64[us]
 2   match_type         283678 non-null  str
 3   event_name         283678 non-null  str
 4   innings            283678 non-null  int64
 5   batting_team       283678 non-null  str
 6   bowling_team       283678 non-null  str
 7   over               283678 non-null  int64
 8   ball               283678 non-null  int64
 9   ball_no            283678 non-null  float64
 10  batter             283678 non-null  str
 11  bat_pos            283678 non-null  int64
 12  runs_batter        283678 non-null  int64
 13  balls_faced        283678 non-null  int64
 14  bowler             283678 non-null  str
 15  valid_ball         283678 non-null  int64
 16  runs_extras        283678 non-null  int64
 17  runs_total         283678 non-null  int64
 18  runs_bowler        283678 non-null  int64
 19  runs_not_boundary  283678 non-null  bool
 20  extra_type         283678 non-null  str
 21  non_striker        283678 non-null  str
 22  non_striker_pos    283678 non-null  int64
 23  wicket_kind        283678 non-null  str
 24  player_out         283678 non-null  str
 25  fielders           283678 non-null  str
 26  runs_target        136510 non-null  float64
 27  review_batter      907 non-null     str
 28  team_reviewed      907 non-null     str
 29  review_decision    283678 non-null  str
 30  umpire             283678 non-null  str
 31  umpires_call       283678 non-null  bool
 32  player_of_match    283678 non-null  str
 33  match_won_by       283678 non-null  str
 34  win_outcome        278954 non-null  str
 35  toss_winner        283678 non-null  str
 36  toss_decision      283678 non-null  str
 37  venue              283678 non-null  str
 38  city               283678 non-null  str
 39  day                283678 non-null  int64
 40  month              283678 non-null  int64
 41  year               283678 non-null  int64
 42  season             283678 non-null  str
 43  gender             283678 non-null  str
 44  team_type          283678 non-null  str
 45  superover_winner   3896 non-null    str
 46  result_type        4724 non-null    str
 47  method             3890 non-null    str
 48  balls_per_over     283678 non-null  int64
 49  overs              283678 non-null  int64
 50  event_match_no     283678 non-null  str
 51  stage              283678 non-null  str
 52  match_number       283678 non-null  str
 53  team_runs          283678 non-null  int64
 54  team_balls         283678 non-null  int64
 55  team_wicket        283678 non-null  int64
 56  new_batter         13593 non-null   str
 57  batter_runs        283678 non-null  int64
 58  batter_balls       283678 non-null  int64
 59  bowler_wicket      283678 non-null  int64
 60  batting_partners   283678 non-null  str
 61  next_batter        13593 non-null   str
 62  striker_out        283678 non-null  bool
 63  total_balls        283678 non-null  int64
 64  is_boundary        283678 non-null  int64
 65  is_wicket          283678 non-null  int64
 66  strike_rate        274340 non-null  float64
dtypes: bool(3), datetime64[us](1), float64(3), int64(26), str(34)
memory usage: 139.3 MB

In [21]:
df.to_csv('../data/processed/ipl_cleaned.csv', index=False)